### ISSUE TITLE
for better read/send message

### ISSUE THREAD

**Issue by unobayu** [morcibacsi/PSAVanCanBridgeHW#1]
after some trial. the hardware fail to read van bus data. also some problem (reboot) when send data. after measuring the data line in the car,there already have resistance. so i have to remove terminating resistor in the both tranceiver. now the hw11 is working good

**Comment by morcibacsi** [comment]
Glad you make it work. I suggest to start with the setup what can be seen on the photos as I used it like that in my car. It is easier to add components later anyways than removing them.

**Comment by DenGorobets** [comment]
Hi, can you answer a few questions?
I also have a VAN multimedia bus on my 2004 car. The head unit has a QUADLOCK connector (not ISO) and an on-board computer display with a 6-pin connector. I bought an Android device to replace the head unit, which in the kit has a Raise CAN emulator. When connected, of course, nothing works due to different buses. Will your device allow the full functioning of the Android device? And is it necessary to buy an on-board computer display that works on the CAN-bus?

**Comment by morcibacsi** [comment]
@DenGorobets This means you have a monochrome RT3 navigation system. If you remove your original head unit, unfortunately that display will stop working. This is because those systems are a little bit funny: The RT3 communicates on the VAN bus however the display has a CAN bus connection towards the head unit. So the RT3 is translating the VAN bus packets for the display. But reverse engineering the CAN communication for that display would be a pain (I've tried it, but it just doesn't worth the effort). So in my opinion it is easier to just replace the display with a newer one. The navigation part would stop working anyways without the RT3. I assume you would like to keep the remote stalk function for your new Android head unit. My device is capable of translating the VAN bus packet of the remote stalk to the corresponding CAN packet. So if you would set the correct car type (Peugeot with CAN bus) in your Android system then most probably it would work.

**Comment by DenGorobets** [comment]
Thank you for the explanation. Android device does not start when the ignition is turned on. If I understand correctly, it’s all because the CAN emulator does not understand that when you turn the key on the VAN bus, a command is sent to turn on the head unit, which the emulator does not understand.
Based on your answer, it is possible without using your development to connect the on-board computer display from the Peugeot 407, which will be controlled by the CAN emulator of the Android device. Right?

**Comment by morcibacsi** [comment]
> Android device does not start when the ignition is turned on

Well that is another problem then. These aftermarket devices don't need ignition signal to work. If you connect to a power supply it should even turn on outside a car. What is the exact model number of the device?

> Based on your answer, it is possible without using your development to connect the on-board computer display from the Peugeot 407, which will be controlled by the CAN emulator of the Android device. Right?

Not quite. If you would like to install a display from a 407 then you definitely need my VAN-CAN bridge. The CAN device inside the Android head units don't send the data for those displays to boot up.

**Comment by DenGorobets** [comment]
There is no exact name, I bought it at this link: https://aliexpress.ru/item/33035372080.html?spm

There are two connection cables in the kit: from ISO to 16 pin in an Android device, from QUADLOCK to 16 pin in an Android device.
In both cases, there are three wires to power the device: black - ground, yellow - permanent + 12V and red - when applying + 12V to the red wire, the device starts up (if you remove the device from the red + 12V, it falls asleep after 30 seconds).
In the adapter with ISO, the red cable is connected directly to the Android device.
In the adapter with QUADLOCK, the red cable is connected from the CAN emulator to the Android device.
Based on this, I suggested that it is the KAN emulator that launches the Android device when the ignition is turned on.

I do not exclude the option that the emulator is not working, there is no way to check it.

**Comment by morcibacsi** [comment]
I see now. That quadlock connector you got with your Android device is for cars made after 2005 with CAN bus. In those cars there is no switched 12V in the quadlock connector, so most probably in those cars ignition signal from the CAN bus is used to turn on the device. For you the simplest thing would be to connect the red cable to the VAN+ pin which is I believe the A9 pin on the quadlock. That way your android unit would boot up when you open the car. And would go to sleep after a few minutes when you close it.

**Comment by DenGorobets** [comment]
This is a great option for the first time. Thank you so much for the consultation!
